### ISSUE TITLE
Max version will be hit next year (2021) when using automatic date formatter

### ISSUE THREAD

**Issue by steliyan** [moallemi/gradle-advanced-build-version#51]
According to[ Android Studio pages](https://developer.android.com/studio/publish/versioning), the maximum version allowed version is:
`2100000000`

When using the automatic date formatted the limit will be hit on January the 1st 2021 as the version would become:
`2101010000`.

Do you have any internal info that they would bump the max version or we're pretty much screwed if we used this versioning scheme?

Greetings, Steliyan.

**Comment by edgar-zigis** [comment]
We are already screwed :) hit that limit now, need to think about the workaround.

**Comment by moallemi** [comment]
Sorry to reach out to you late. I will fix it ASAP. BTW the library is open source. feel free to suggest a solution.

For now you can use a workaround like:
```
codeOptions {
            lastLegacyCode YOUR_LAST_USED_VERSION_CODE
            versionCodeType 'GIT_COMMIT_COUNT'
        }
```

**Comment by ldimitroff** [comment]
Can be something like this

```
    codeOptions {
        versionCodeType 'GIT_COMMIT_COUNT'
    }
```

```
android {
    defaultConfig {
        ...
        versionCode getBuildNumber()
        ...
    }
}
```

```
def getBuildNumber() {
    def LAST_BUILD_RELEASED = 2012032003 //Change to your last used version code DATE
    LAST_BUILD_RELEASED + advancedVersioning.versionCode
}
```

**Comment by moallemi** [comment]
@ldimitroff No need to define a new function. As I [mentioned before](https://github.com/moallemi/gradle-advanced-build-version/issues/51#issuecomment-753830393) there is a property for that `lastLegacyCode`

**Comment by piotrkst** [comment]
One could overwrite the first two digits that are responsible for the year and decrement them by 20 (could be variable of the project starting year) which will give you a nice lifespan of 20 years. You could also manipulate the next two digits responsible for a month and since they only go from 00 to 12 there is plenty of space to store year information (you could have 00-96 to store up to 8 years) which would increase the lifespan of the implementation up to 160 years which is more than enough.
